### PR TITLE
Django 4.x support

### PR DESCRIPTION
**Pull request by filipweidemann**
This PR adds test coverage for Django 4.x & Python 3.10 to the tox environment to ensure proper function when using those versions.

All checks should be green in CI, therefore I also bumped the supported versions in `setup.py`. 

It would be really cool if you could merge this and release a new version @charettes. 
Really loving this simple library :)

### CODE REVIEW

**Comment by charettes** [comment]
Thanks for the PR @filipweidemann appreciated. Do you think you could drop support for Python 3.6, any Django version < 3.2, and test against Python 3.11 as well.

Here's a commit that did just that https://github.com/charettes/django-seal/commit/837d289dc9829e43fc0409bf153f20bd94e10156.

Happy to push a new release once tests are passing.

**Comment by filipweidemann** [comment]
Sure, I also bumped the release action to Python 3.7 if that's okay. 
I saw you did the same thing over at django-seal so I figured it would probably be okay.

Could you please run the tests once more? Thank you! :)

**Comment by charettes** [comment]
@filipweidemann [just released 1.8](https://pypi.org/project/django-polymodels/1.8.0/).

**Comment by filipweidemann** [comment]
@charettes wow that was fast! 
Django 4.2 update path is unblocked now, tomorrow will be fun I guess!

Thank you for your time & we'll surely open PRs for 5.2 as well (when it drops) 🙂

**Comment by charettes** [comment]
np, thank you for submitting the changes.

**Pull request merged**
