### PR TITLE
Fix caching bug after type_casting a child model

### PR DESCRIPTION
**Pull request by gavinwahl**
This was broken in e62412b701331467cb135a3f9fc7b0b706e77843.

The fix I did is pretty hacky -- hopefully you will be able to use the test to write a cleaner fix.

### CODE REVIEW

**Comment by gavinwahl** [comment]
This is strange, the test I wrote fails locally but not on travis (I tried to run the tests on travis, without the fix, expecting a failure: https://travis-ci.org/fusionbox/django-polymodels), but it actually passes on travis unexpectedly. Any idea what would cause that?

**Comment by charettes** [comment]
When are you hitting this bug? Is it during migrations? Are you sure all you models are registered to apps?

**Comment by gavinwahl** [comment]
It's in regular code, not migrations, and the models are registered. Does the test not fail for you when you remove the fix?

It makes sense when you look at the loop in __get__ -- 'owner' is the subclass, not the polymorphic base model, so the cache doesn't get filled in for any of its siblings.

**Comment by charettes** [comment]
The test pass locally without the fix for me on Django 1.9.1.

```
python -m django test --settings=tests.settings -v2
Creating test database for alias 'default' (':memory:')...
Operations to perform:
  Synchronize unmigrated apps: polymodels, tests
  Apply all migrations: contenttypes
Synchronizing apps without migrations:
  Creating tables...
    Creating table polymodels_zoo
    Creating table polymodels_animal
    Creating table polymodels_mammal
    Creating table polymodels_monkey
    Creating table polymodels_trait
    Creating table polymodels_snake
    Running deferred SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
test_equality (tests.test_fields.ContentTypeReferenceTests) ... ok
test_repr (tests.test_fields.ContentTypeReferenceTests) ... ok
test_retreival (tests.test_fields.ContentTypeReferenceTests) ... ok
test_default_value (tests.test_fields.PolymorphicTypeFieldTests) ... ok
test_description (tests.test_fields.PolymorphicTypeFieldTests) ... ok
test_field_deconstruction (tests.test_fields.PolymorphicTypeFieldTests) ... ok
test_formfield_issues_no_queries (tests.test_fields.PolymorphicTypeFieldTests) ... ok
test_invalid_polymorphic_model (tests.test_fields.PolymorphicTypeFieldTests) ... ok
test_invalid_type (tests.test_fields.PolymorphicTypeFieldTests) ... ok
test_limit_choices_to (tests.test_fields.PolymorphicTypeFieldTests) ... ok
test_unresolved_relationship_formfield (tests.test_fields.PolymorphicTypeFieldTests) ... ok
test_valid_proxy_subclass (tests.test_fields.PolymorphicTypeFieldTests) ... ok
test_valid_subclass (tests.test_fields.PolymorphicTypeFieldTests) ... ok
test_checks (tests.test_models.BasePolymorphicModelTest) ... ok
test_type_cast (tests.test_models.BasePolymorphicModelTest) ... ok
test_type_cast_on_child_class (tests.test_models.BasePolymorphicModelTest) ... ok
test_select_subclasses (tests.test_related.RelatedManagerTest) ... ok
test_default_instance_type (tests.test_forms.PolymorphicModelFormTests) ... ok
test_instance_based_form_creation (tests.test_forms.PolymorphicModelFormTests) ... ok
test_invalid_provided_instance (tests.test_forms.PolymorphicModelFormTests) ... ok
test_retreival_from_class (tests.test_forms.PolymorphicModelFormTests) ... ok
test_improperly_configured (tests.test_managers.PolymorphicManagerTest) ... ok
test_proxy_filtering (tests.test_managers.PolymorphicManagerTest) ... ok
test_exclude_subclasses (tests.test_managers.PolymorphicQuerySetTest) ... ok
test_select_subclasses (tests.test_managers.PolymorphicQuerySetTest) ... ok
test_dynamic_model_creation_cache_busting (tests.test_models.SubclassAccessorsTests) ... ok

----------------------------------------------------------------------
Ran 26 tests in 0.179s

OK
Destroying test database for alias 'default' (':memory:')...
```

**Comment by charettes** [comment]
Ahh it fails when run in isolation, looking into it.

**Comment by gavinwahl** [comment]
This is super weird, this is what I did and get:

```
$ mktmpenv 
$ pip install django==1.9.1
$ pip install -e ~/django-polymodels/
$ python -m django test --settings=tests.settings -v2
Creating test database for alias 'default' (':memory:')...
Operations to perform:
  Synchronize unmigrated apps: polymodels, tests
  Apply all migrations: contenttypes
Synchronizing apps without migrations:
  Creating tables...
    Creating table polymodels_zoo
    Creating table polymodels_animal
    Creating table polymodels_mammal
    Creating table polymodels_monkey
    Creating table polymodels_trait
    Creating table polymodels_snake
    Running deferred SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
test_improperly_configured (tests.test_managers.PolymorphicManagerTest) ... ok
test_proxy_filtering (tests.test_managers.PolymorphicManagerTest) ... ok
test_exclude_subclasses (tests.test_managers.PolymorphicQuerySetTest) ... ok
test_select_subclasses (tests.test_managers.PolymorphicQuerySetTest) ... FAIL
test_select_subclasses (tests.test_related.RelatedManagerTest) ... FAIL
test_default_instance_type (tests.test_forms.PolymorphicModelFormTests) ... ok
test_instance_based_form_creation (tests.test_forms.PolymorphicModelFormTests) ... ok
test_invalid_provided_instance (tests.test_forms.PolymorphicModelFormTests) ... ok
test_retreival_from_class (tests.test_forms.PolymorphicModelFormTests) ... ok
test_equality (tests.test_fields.ContentTypeReferenceTests) ... ok
test_repr (tests.test_fields.ContentTypeReferenceTests) ... ok
test_retreival (tests.test_fields.ContentTypeReferenceTests) ... ok
test_default_value (tests.test_fields.PolymorphicTypeFieldTests) ... ok
test_description (tests.test_fields.PolymorphicTypeFieldTests) ... ok
test_field_deconstruction (tests.test_fields.PolymorphicTypeFieldTests) ... ok
test_formfield_issues_no_queries (tests.test_fields.PolymorphicTypeFieldTests) ... ok
test_invalid_polymorphic_model (tests.test_fields.PolymorphicTypeFieldTests) ... ok
test_invalid_type (tests.test_fields.PolymorphicTypeFieldTests) ... ok
test_limit_choices_to (tests.test_fields.PolymorphicTypeFieldTests) ... ok
test_unresolved_relationship_formfield (tests.test_fields.PolymorphicTypeFieldTests) ... ok
test_valid_proxy_subclass (tests.test_fields.PolymorphicTypeFieldTests) ... ok
test_valid_subclass (tests.test_fields.PolymorphicTypeFieldTests) ... ok
test_checks (tests.test_models.BasePolymorphicModelTest) ... ok
test_type_cast (tests.test_models.BasePolymorphicModelTest) ... ok
test_type_cast_on_child_class (tests.test_models.BasePolymorphicModelTest) ... FAIL
test_dynamic_model_creation_cache_busting (tests.test_models.SubclassAccessorsTests) ... ok

======================================================================
FAIL: test_select_subclasses (tests.test_managers.PolymorphicQuerySetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_managers.py", line 26, in test_select_subclasses
    self.assertEqual(animals.query.select_related, animals_expected_query_select_related)
AssertionError: {'snake': {}} != {u'mammal': {u'monkey': {}}, u'snake': {}}
- {'snake': {}}
+ {u'mammal': {u'monkey': {}}, u'snake': {}}

======================================================================
FAIL: test_select_subclasses (tests.test_related.RelatedManagerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_related.py", line 19, in test_select_subclasses
    self.assertIn(yeti, zoo_animals)
AssertionError: <Mammal: Yeti> not found in [<Animal: Yeti>]

======================================================================
FAIL: test_type_cast_on_child_class (tests.test_models.BasePolymorphicModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_models.py", line 113, in test_type_cast_on_child_class
    self.assertEqual(snake.animal_ptr.type_cast(), snake)
AssertionError: <Animal: > != <Snake: >

----------------------------------------------------------------------
Ran 26 tests in 0.060s

FAILED (failures=3)
Destroying test database for alias 'default' (':memory:')...
```

**Comment by charettes** [comment]
@gavinwahl, can you confirm the fix I pushed fixes your regression?

**Comment by gavinwahl** [comment]
It works, thanks. Any idea why the tests weren't failing?

**Comment by charettes** [comment]
Well the test you suggested adding failed in isolation because the the subclass accessors were not all cached at this point but I cannot explain all of your local failures :/

I'll add a commit to make sure the cache is cleaned between each test case and see if something else work.

**Pull request closed without merging**
